# Generated by Django 4.1.3 on 2022-12-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deportes', '0002_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('equipo', models.CharField(max_length=40)),
                ('edad', models.CharField(max_length=2)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('posicion', models.CharField(max_length=20)),
            ],
        ),
    ]
